### ISSUE TITLE
Wrong test 'invalid date-time (missing colon in timezone part)'

### ISSUE THREAD

**Issue by alexpts** [csnover/js-iso8601#25]
ok(isNaN(Date.parse('1970-01-01T00:00:00+0630')), 'invalid date-time (missing colon in timezone part)');

'1970-01-01T00:00:00+0630' it is correct time in ISO8601

https://tools.ietf.org/html/rfc3339
time-numoffset = ("+" / "-") time-hour [[":"] time-minute]
time-zone = "Z" / time-numoffset

**Comment by csnover** [comment]
This is not a bug. Ecmascript uses a restricted variant of iso9601. Use the LAX branch.
