### ISSUE TITLE
Local times

### ISSUE THREAD

**Issue by rxaviers** [csnover/js-iso8601#29]
According to [ISO 8601 definition](http://metric1.org/8601.pdf), the cases below should be considered local times, not Zulu (UTC) times... Right?

![screen shot 2017-02-07 at 11 37 09 am](https://cloud.githubusercontent.com/assets/967155/22693301/d7c5f392-ed29-11e6-9642-d4787fbf2202.png)

```js
strictEqual(Date.parse('2001-02-03T04:05'),        Date.UTC(2001, 1, 3, 4, 5, 0, 0), '2001-02-03T04:05');
strictEqual(Date.parse('2001-02-03T04:05:06'),     Date.UTC(2001, 1, 3, 4, 5, 6, 0), '2001-02-03T04:05:06');
strictEqual(Date.parse('2001-02-03T04:05:06.007'), Date.UTC(2001, 1, 3, 4, 5, 6, 7), '2001-02-03T04:05:06.007');
```
https://github.com/csnover/js-iso8601/blob/d0d8c37028435e1cd72205d6ab2610ba90cff166/tests/test.js#L36-L38

**Comment by csnover** [comment]
https://github.com/csnover/js-iso8601/issues/14
